# Root configuration placeholder for Worker services. Each Worker/service
# defines its own `wrangler.toml` in its folder (e.g.,
# `services/api-worker/wrangler.toml`).

# Example snippet for a service-level wrangler.toml:
# name = "c360-api"
# main = "src/index.ts"
# compatibility_date = "2024-11-01"
# [observability]
# enabled = true
# [[d1_databases]]
# binding = "DB"
# database_name = "c360_prod"
# database_id = "3cdf8d89-79b4-42de-83db-5446d97d49e8"
