# Root placeholder. Each Worker/service will define its own wrangler.toml
# in its respective folder (e.g., services/api-worker/wrangler.toml).

# Example snippet for a service-level wrangler.toml:
# name = "c360-api"
# main = "src/index.ts"
# compatibility_date = "2024-11-01"
# [observability]
# enabled = true
# [[d1_databases]]
# binding = "DB"
# database_name = "c360_dev"
# database_id = "<uuid>"
