name = "c360-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "c360_dev"
database_id = "e5539a46-e857-4677-8ba4-ff5798cc0e25"

[[kv_namespaces]]
binding = "KV"
id = "a258aa13ae6542d28b2f3200b206cc69" # TODO: replace with real KV id

[vars]
# Local/dev default CORS (override in envs below). Use either CORS_ORIGIN (single) or CORS_ORIGINS (comma-separated).
CORS_ORIGIN = "http://localhost:5173"
JWT_SECRET = "devsecret"

# Staging environment
[env.staging]
name = "c360-api-staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "c360_staging"
database_id = "448cd3be-4117-4d6c-bb44-cf89ec21637f" 

[[env.staging.kv_namespaces]]
binding = "KV"
id = "3c5041f70b394827b3e853c18d03e290" # TODO: replace with real KV id

[env.staging.vars]
# Allow only staging app origins
CORS_ORIGIN = "https://staging.app.example.com" # single-origin fallback; not inherited from top-level
CORS_ORIGINS = "https://staging.app.example.com,https://staging.admin.example.com"

# Production environment
[env.production]
name = "c360-api-prod"

[[env.production.d1_databases]]
binding = "DB"
database_name = "c360_prod"
database_id = "3cdf8d89-79b4-42de-83db-5446d97d49e8" 

[[env.production.kv_namespaces]]
binding = "KV"
id = "9ac7ff65e9b94796b007b2bc156a7d2d" # TODO: replace with real KV id

[env.production.vars]
# Lock down to exact production origins
CORS_ORIGIN = "https://app.example.com" # single-origin fallback; not inherited from top-level
CORS_ORIGINS = "https://app.example.com,https://admin.example.com"

# Note: Do NOT put API_TOKEN in this file. Set it securely via:
#   wrangler secret put API_TOKEN
