name = "c360-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "c360_dev"
database_id = "00000000-0000-0000-0000-000000000000" # TODO: replace with real ID

[[kv_namespaces]]
binding = "KV"
id = "00000000000000000000000000000000" # TODO: replace with real KV id

[vars]
# Local/dev default CORS (override in envs below). Use either CORS_ORIGIN (single) or CORS_ORIGINS (comma-separated).
CORS_ORIGIN = "http://localhost:5173"

# Staging environment
[env.staging]
name = "c360-api-staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "c360_staging"
database_id = "11111111-1111-1111-1111-111111111111" # TODO: replace with real ID

[[env.staging.kv_namespaces]]
binding = "KV"
id = "11111111111111111111111111111111" # TODO: replace with real KV id

[env.staging.vars]
# Allow only staging app origins
CORS_ORIGINS = "https://staging.app.example.com,https://staging.admin.example.com"

# Production environment
[env.production]
name = "c360-api-prod"

[[env.production.d1_databases]]
binding = "DB"
database_name = "c360_prod"
database_id = "22222222-2222-2222-2222-222222222222" # TODO: replace with real ID

[[env.production.kv_namespaces]]
binding = "KV"
id = "22222222222222222222222222222222" # TODO: replace with real KV id

[env.production.vars]
# Lock down to exact production origins
CORS_ORIGINS = "https://app.example.com,https://admin.example.com"

# Note: Do NOT put API_TOKEN in this file. Set it securely via:
#   wrangler secret put API_TOKEN
